name: gpi
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.7  # remove if using CPU-only setup
  - tqdm=4.66.1
  - scikit-video=1.1.11
  - opencv=4.7.0
  - pygame=2.5.2
  - pymunk=6.6.0
  - shapely=1.8.5
  - scikit-image=0.20.0
  - zarr=2.15.0
  - gdown=4.7.1
  - gym=0.26.2
